run:
  tests: false
linters:
  enable:
    - revive
    - staticcheck
linters-settings:
  revive:
    ignore-generated-header: true
    rules:
      - name: cognitive-complexity
        arguments: [10]
      - name: cyclomatic
        arguments: [5]
