before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: try-goreleaser
    goos:
      - linux
    goarch:
    - amd64

kos:
  - id: ko-try-goreleaser
    build: try-goreleaser
    repository: ghcr.io/tonimaru/try-goreleaser
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    preserve_import_paths: false
    platforms:
    - linux/amd64
